<?php 
 include('../lib/main-header.php');
?>
<ul class="breadcrumb">
    <li><a href="/">Home</a></li>
  <li><a href="/categories/">Categories</a></li>
    <li class="active">Subjective (History) Elements</li>
</ul>

<div id="container" class="container">
<ul class="nav nav-pills nav-stacked">
					<li><a href="/child-health/1-week-hx/">1 Week History</a></li>
					<li><a href="/child-health/2-month-hx/">2 Month History</a></li>
					<li><a href="/child-health/4-month-hx/">4 Month History</a></li>
					<li><a href="/child-health/6-month-hx/">6 Month History</a></li>
					<li><a href="/child-health/12-month-hx/">12 Month History</a></li>
					<li><a href="/child-health/15-month-hx/">15 Month History</a></li>
					<li><a href="/child-health/2-year-hx/">2 Year History</a></li>
					<li><a href="/child-health/2-to-6-year-prevention-hx/">2 to 6 Year Prevention History</a></li>
					<li><a href="/child-health/3-year-hx/">3 Year History</a></li>
					<li><a href="/child-health/4-year-hx/">4 Year History</a></li>
					<li><a href="/child-health/5-year-hx/">5 Year History</a></li>
					<li><a href="/child-health/6-to-10-year-hx/">6 to 10 Year History</a></li>
					<li><a href="/child-health/11-to-14-year-hx/">11 to 14 Year History</a></li>
					<li><a href="/child-health/15-to-18-year-history/">15 to 18 Year History</a></li>
					<li><a href="/digestive-system/abdominal-pain-history/">Abdominal Pain History</a></li>
					<li><a href="/neurological/aloc-hx/">Altered Level of Consciousness History</a></li>
					<li><a href="/neurological/acute-neuro-hx/">Acute Neurological Change History</a></li>
					<li><a href="/respiratory/asthma-hx/">Asthma History</a></li>
					<li><a href="/injury/assault-history/">Assault History</a></li>				
					<li><a href="/musculoskeletal/back-pain-s-o/">Back Pain History and Exam</a></li>
					<li><a href="/injury/bite-wound-history/">Bite Wound History</a></li>
					<li><a href="/respiratory/bronchitis-history/">Bronchitis History</a></li>
					<li><a href="/injury/burn-hx/">Burn History</a></li>
					<li><a href="/cardiovascular/chest-pain-history/">Chest Pain History</a></li>
					<li><a href="/elder-care/cognitive-problems-history/">Cognitive Problems History</a></li>
					<li><a href="/respiratory/cough-history/">Cough History</a></li>
					<li><a href="/women/initiating-contraception/" 
	target="_blank">(Initiating) Contraception History</a></li>
					<li><a href="/respiratory/cough-history/" 
	target="_blank">Cough History</a></li>
					<li><a href="/child-health/croup-history/">Croup History</a></li>
					<li><a href="/endocrine-metabolic/dm-history/">Diabetes History</a></li>
					<li><a href="/endocrine-metabolic/diabetic-foot-ulcer-history/">Diabetic Foot Ulcer History</a></li>
					<li><a href="/respiratory/dyspnea-history/">Dyspnea History</a></li>
					<li><a href="/cardiovascular/fall-or-syncopal-episode-history/">Fall or Syncopal Episode History</a></li>
					<li><a href="/women/female-genitourinary-hx/">Female Genitourinary Symptoms History</a></li>
					<li><a href="/women/female-ros/">Female Review of Systems</a></li>
					<li><a href="/general/fever-history/">Fever History</a></li>
					<li><a href="/child-health/fever-history/">Fever History (Pediatric)</a></li>					
					<li><a href="/child-health/fussiness-history/">Fussiness History</a></li>
					<li><a href="/digestive-system/gastroenteritis-history/">Gastroenteritis History 1</a></li>
					<li><a href="/digestive-system/gastroenteritis-history-2/">Gastroenteritis History 2</a></li>
					<li><a href="/elder-care/geriatric-comprehensive-assessment-history/">Geriatric Comprehensive Assessment (History)</a></li>
					<li><a href="/digestive-system/gi-bleeding-hx/">GI Bleeding History</a></li>
					<li><a href="/injury/head-injury-history/">Head Injury History</a></li>
					<li><a href="/neurological/headache-hx/">Headache History</a></li>
					<li><a href="/general/history-of-present-illness/">History of Present Illness</a></li>
					<li><a href="/infectious/influenza-history/">Influenza History</a></li>
					<li><a href="/injury/injury-history/">Injury History</a></li>
					<li><a href="/musculoskeletal/lower-back-pain-history/">Low Back Pain History</a></li>
					<li><a href="/injury/lower-extremity-hx/">Lower Extremity Pain/Injury History</a></li>
					<li><a href="/men/urinary-hx/">Male Genitourinary Symptoms History</a></li>
					<li><a href="/elder-care/medicare-history/">(Welcome to) Medicare History</a></li>				
					<li><a href="/injury/mva-hx/">Motor Vehicle Accident History</a></li>
					<li><a href="/general/pain-hx/">Pain History</a></li>
					<li><a href="/general/pain-history/">Pain History - Pain Scales</a></li>
					<li><a href="/cardiovascular/palpitations-history/">Palpitations History</a></li>
					<li><a href="/ear-nose-throat/pharyngitis-history/">Pharyngitis History</a></li>
					<li><a href="/cardiovascular/pame-history/">Pre-Anesthesia or Pre-Operative Medical Examination History</a></li>
					<li><a href="/pregnancy/preg-symptoms/">Pregnancy Related Symptoms History</a></li>
					<li><a href="/mental-health/bathe-technique/">Psychosocial History - BATHE Technique</a></li>
					<li><a href="/skin/rash-history/">Rash History</a></li>
					<li><a href="/skin/scabies-hx/">Scabies History</a></li>
					<li><a href="/neurological/seizure-history/">Seizure History</a></li>
					<li><a href="/eye/stye-history">Stye History</a></li>
					<li><a href="/general/travel-counseling-history/">Travel Counseling History</a></li>
					<li><a href="/musculoskeletal/upper-back-pain-history/">Upper Back Pain History</a></li>
					<li><a href="/injury/upper-extremity-hx/">Upper Extremity Pain/Injury History</a></li>
					<li><a href="/women/uti-history/">Urinary Tract Infection (UTI) History</a></li>
					<li><a href="/women/vaginitis-history/">Vaginitis History</a></li>
					<li><a href="/infectious/varicella-history/">Varicella History</a></li>	
					<li><a href="/infectious/viral-infection-hx/">Viral Infection History</a></li>									</ul>
</div>